### ISSUE TITLE
Balancing mode not respected after a fault

### ISSUE THREAD

**Issue by nitrousnrg** [luna-cycle/vesc_bms_fw#9]
Here are the steps to reproduce the problem:

* Set balancing mode to BALANCE_MODE_ALWAYS
* Get the pack into an cell overvoltage fault (4.25V)
* Check if the pack keeps bleeding the overvolted cell (It should)
* Heavy balancing will produce a hardware overtemperature (AFE reaches 75°C)
* Balancing mode will switch to balance_mode_disabled
* Temps will cool down below the 5°C hysteresis (70°C) and the balancing mode switches to **BALANCE_MODE_CHARGING_ONLY**. This is wrong! In the first step we set it to BALANCE_MODE_ALWAYS

This bug results in a pack that is above 4.2V and does nothing to bleed off the cell that had an overvoltage. I have to manually write the MODE_ALWAYS several times until it finally goes below 4.2V

**Comment by diegosarli** [comment]
In the prev code, during faults, the balance configuration was changed according to the fault (balance always during OV, balance disable during over temp). This approach implies to store the current balance config change it for a new one (always or disable) and return to the original configuration once the fault is cleared. If there is nested faults this approach is complicated and faults track is difficult. 
New approach was pushed, the balance configuration during faults is not touched, but the balance is forced (for OV) or inhibited (for temp of UV) in the balance thread. This is code is more compact and simpler.

https://github.com/luna-cycle/vesc_bms_fw/commit/b16fb7ee8626ebcf7817e765871e2ca171679e67
